'use client';

import Script from 'next/script'
import { Inter } from 'next/font/google'
import { SnackbarProvider } from 'notistack';
import PrivacyControls from '@/components/PrivacyControls'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <PrivacyControls />
      <body className={inter.className}>
        <SnackbarProvider>
          {children}
        </SnackbarProvider>
      </body>
    </html>
  )
}

export default RootLayout;