name: CodeAnt CI Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  codeant_scan:
    name: Run CodeAnt CI scan
    runs-on: ubuntu-latest
    if: ${{ vars.CODEANT_ENABLED == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run CodeAnt CI Scan
        uses: CodeAnt-AI/codeant-ci-scan-action@v0.0.5
        with:
          access_token: ${{ secrets.CODEANT_API_TOKEN }}
