run: |
  mkdir -p "/home/runner/work/leads-db/leads-db"
  cd "/home/runner/work/leads-db/leads-db"
  git init
  git config user.name IsaacBell
  git config user.email isaacbell388@gmail.com
  
  # Add files from ZONES_DIR
  cd "$ZONES_DIR"
  git add ./*
  
  # Add files from DAILY_DIR
  cd "$GITHUB_WORKSPACE" # Return to the leads-db repository directory
  git add "$DAILY_DIR/today_new.gz" "$DAILY_DIR/yesterday_new.gz"
  
  git commit -a -m "updating bot - $(date '+%Y/%m/%d')"
  git pull
  git push
