name: Daily updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      
    - name: Checkout nrd-poll repository
      uses: actions/checkout@v3
      with:
        repository: IsaacBell/nrd-poll
        token: ${{ secrets.SYNC_TOKEN }}
        path: nrd-poll
      
    - name: Debug - Check nrd-poll checkout
      run: |
        echo "Contents of $GITHUB_WORKSPACE:"
        ls -la $GITHUB_WORKSPACE
        echo "Contents of $GITHUB_WORKSPACE/nrd-poll:"
        ls -la $GITHUB_WORKSPACE/nrd-poll
        
    - name: What time is it?
      run: |
        date -u
        TZ="Europe/Paris" date
        
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install prerequisites
      run: |
        sudo apt -qq install fd-find
        
    - name: Prepare global variables
      run: |
        echo "ZONES_DIR=$GITHUB_WORKSPACE/data/zones" >> $GITHUB_ENV
        echo "DAILY_DIR=$GITHUB_WORKSPACE/data/daily" >> $GITHUB_ENV
        echo "SYNC_DIR=$GITHUB_WORKSPACE/nrd-poll" >> $GITHUB_ENV
        
    - name: Debug - Check SYNC_DIR path
      run: |
        echo "SYNC_DIR path:"
        echo $SYNC_DIR
        echo "Contents of SYNC_DIR:"
        ls -la $SYNC_DIR
        
    - name: Sync data
      run: |
        mkdir -p "$DAILY_DIR"
        
        if [ -f "$SYNC_DIR/today_new.gz" ]; then
          cp "$SYNC_DIR/today_new.gz" "$DAILY_DIR/today_new.gz"
          echo "today_new.gz synced successfully"
        else
          echo "Error: today_new.gz not found in the nrd-poll repository"
          exit 1
        fi
        
        if [ -f "$SYNC_DIR/yesterday_new.gz" ]; then
          cp "$SYNC_DIR/yesterday_new.gz" "$DAILY_DIR/yesterday_new.gz"
          echo "yesterday_new.gz synced successfully"
        else
          echo "Error: yesterday_new.gz not found in the nrd-poll repository"
          exit 1
        fi
        
    - name: Commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        git add "$DAILY_DIR/today_new.gz" "$DAILY_DIR/yesterday_new.gz"
        
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync data from nrd-poll repository"
          git push
        fi
  